server:
  port: 9494

spring:
  application:
    name: springcloud-zuul

#eureka配置
eureka:
  client:
    service-url:  #服务的url
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-zuul-9494
    prefer-ip-address: true

#网关配置
zuul:
  routes:
    guihxRoutes: #这里自己随便起，下面两个名字固定
      serviceId: springcloud-provider-dept
      path: /jkl/**
  ignored-services: springcloud-provider-dept #不让使用这个，要用就用我上面设定的

info:
  app.name: app
  boss.name: guihx

logging:
  config: classpath:logback.xml
