server:
  port: 8080

#eureka配置
eureka:
  client:
    register-with-eureka: false #表示是否向服务端注册自己
    service-url:  #服务的url
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

logging:
  config: classpath:logback.xml