server:
  port: 7003

#eureka配置
eureka:
  instance:
    hostname: localhost #eureka服务端实例名称
  client:
    register-with-eureka: false #表示是否向服务端注册自己
    fetch-registry: false #如果为false,表示为自己就是注册中心
    service-url:  #服务的url
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

logging:
  config: classpath:logback.xml